provider "azurerm" {
  features {}
}

# Outputs of the core stack (workspace URL, storage/KV names, SP ids).
# remote-state.auto.tfvars is generated by bootstrap.ps1 (gitignored).
data "terraform_remote_state" "core" {
  backend = "azurerm"
  config = {
    resource_group_name  = var.state_resource_group_name
    storage_account_name = var.state_storage_account_name
    container_name       = var.state_container_name
    key                  = "core.tfstate"
  }
}

locals {
  core = data.terraform_remote_state.core.outputs
}

# Workspace-level provider — Azure CLI auth locally, OIDC in CI.
provider "databricks" {
  host = local.core.databricks_workspace_url
}

# Account-level provider — Unity Catalog groups, service principals and
# workspace assignments are account objects, not workspace objects.
provider "databricks" {
  alias      = "account"
  host       = "https://accounts.azuredatabricks.net"
  account_id = var.databricks_account_id
}
