provider "azurerm" {
  features {}
}

# Tenant id for the Databricks account endpoint — resolved from the current
# Azure CLI session, never hardcoded (public repo).
data "azurerm_client_config" "current" {}

# Outputs of the core stack (workspace URL, storage/KV names, SP ids).
# remote-state.auto.tfvars is generated by bootstrap.ps1 (gitignored).
data "terraform_remote_state" "core" {
  backend = "azurerm"
  config = {
    resource_group_name  = var.state_resource_group_name
    storage_account_name = var.state_storage_account_name
    container_name       = var.state_container_name
    key                  = "core.tfstate"
  }
}

locals {
  core = data.terraform_remote_state.core.outputs
}

# Workspace-level provider — Azure CLI auth locally, OIDC in CI.
provider "databricks" {
  host      = local.core.databricks_workspace_url
  auth_type = "azure-cli"
}

# Account-level provider — Unity Catalog groups, service principals and
# workspace assignments are account objects, not workspace objects.
#
# Auth: sp-lakeforge-infra (registered in the account console as account
# admin), NOT the human azure-cli session — the account REST API rejects
# personal Microsoft accounts (MSA). The secret comes from Key Vault, never
# from tfvars or env.
# Read only in account-groups mode: in fallback mode nothing uses the account
# provider, and skipping the read keeps `terraform plan` working from machines
# that cannot reach the private Key Vault (FR-1.8 end state).
data "azurerm_key_vault_secret" "infra_sp" {
  count        = var.enable_account_groups ? 1 : 0
  name         = "sp-infra-client-secret"
  key_vault_id = local.core.key_vault_id
}

provider "databricks" {
  alias               = "account"
  host                = "https://accounts.azuredatabricks.net"
  account_id          = var.databricks_account_id
  azure_client_id     = local.core.infra_sp_client_id
  azure_client_secret = try(data.azurerm_key_vault_secret.infra_sp[0].value, null)
  azure_tenant_id     = data.azurerm_client_config.current.tenant_id
}
