terraform {
  required_version = ">= 1.9"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.30"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 3.4"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.7"
    }
  }

  # Partial config: resource_group_name / storage_account_name / container_name
  # come from infra/backend.hcl (generated by bootstrap.ps1, gitignored).
  backend "azurerm" {
    key = "core.tfstate"
  }
}
